version: "3.7"

services:
  app:
    build: ./sys-stats
    container_name: frontend
    restart: always
    environment: 
      - APP_name=app
    expose:
      - "3000"


  backend:
    build: ./api
    container_name: backend
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:5000"



