FROM node:15-alpine as build
WORKDIR /app
RUN apt -y install wget
RUN apt-get -y update
ENV PATH /app/node_modules/.bin:$PATH
ADD . ./
RUN npm install
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon on;"]
