FROM python

# set the working directory in the container
WORKDIR /app

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip3 install -r requirements.txt

# copy the content of the local directory to the working directory
ADD . /app

# command to run on container start
CMD ["gunicorn", "-b", "0.0.0.0:5000","wsgi:app" ]

